name: End to End Testing

on: [push, pull_request]

jobs:
    test:
        name: Run tests

        runs-on: ubuntu-latest

        steps:
            - name: Checkout on ${{ runner.os }}
              uses: actions/checkout@v3

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.7.0

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.5.0
                  cache: 'yarn'

            - name: Run Cypress
              uses: cypress-io/github-action@v4
              with:
                  command: yarn workspace @kaetram/e2e test:run:record
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
